# Pandas Tutorial

In [1]:
import pandas as pd

df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A","B","C"])

In [2]:
df.head() # Shows the first 5 rows of the dataframe

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [3]:
df.tail(2) # Shows the last 2 rows of the dataframe

   A  B  C
1  4  5  6
2  7  8  9

In [4]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes

## Loading Dataframes from files

In [6]:
coffee = pd.read_csv('./warmup-data/coffee.csv')
bios = pd.read_csv('./data/bios.csv')

## Accessing Data

In [7]:
coffee.sample(5) # Displays 5 random entries from the dataframe

          Day Coffee Type  Units Sold
11   Saturday       Latte          35
5   Wednesday       Latte          25
8      Friday    Espresso          45
13     Sunday       Latte          35
10   Saturday    Espresso          45

In [8]:
coffee.loc[:,["Day","Units Sold"]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [9]:
coffee.iloc[:,[0,1]]

          Day Coffee Type
0      Monday    Espresso
1      Monday       Latte
2     Tuesday    Espresso
3     Tuesday       Latte
4   Wednesday    Espresso
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte
12     Sunday    Espresso
13     Sunday       Latte

In [11]:
coffee.sort_values("Coffee Type", ascending=True)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
2     Tuesday    Espresso          30
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
1      Monday       Latte          15
3     Tuesday       Latte          20
5   Wednesday       Latte          25
7    Thursday       Latte          30
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35

## Filtering Data

In [ ]:
bios.loc[(bios['height_cm'] > 215) & (bios['weight_kg'] > 100), ['name', 'height_cm', 'weight_kg']].sort_values(['height_cm', 'weight_kg'], ascending=[1,1]) #Filters the players with a height > 215 cm and a weight > 100 kg and sort both height and weight in ascending order

                         name  height_cm  weight_kg
6223              Lars Hansen      216.0      105.0
6937           David Robinson      216.0      107.0
123850         Tyson Chandler      216.0      107.0
138671          Ondřej Balvín      216.0      107.0
121694            Salah Mejri      216.0      110.0
6409         Sergey Kovalenko      216.0      111.0
118663         Timofey Mozgov      216.0      113.0
112332    Andreas Glyniadakis      216.0      115.0
6270              Hu Zhangbao      216.0      135.0
6722         Shaquille O'Neal      216.0      137.0
52608         Aleksey Kazakov      217.0      102.0
5583     Paulinho Villas Boas      217.0      106.0
7074           Paulo da Silva      217.0      106.0
112312           Stanko Barać      217.0      110.0
7281         Stojko Vranković      217.0      115.0
5716                 Uwe Blab      218.0      110.0
82100           Frédéric Weis      218.0      110.0
112337          Hamed Haddadi      218.0      110.0
7376      Eurelijus Žukauskas      218.0      115.0
130460               Li Muhao      218.0      115.0
6420            Jānis Krūmiņš      218.0      141.0
118676        Dmitry Musersky      219.0      104.0
107408       Peter John Ramos      219.0      113.0
7188       Vladimir Tkachenko      220.0      110.0
5089       Viktor Pankrashkin      220.0      112.0
6504              Luc Longley      220.0      135.0
120266           Zhang Zhaoxu      221.0      110.0
5673           Gunther Behnke      221.0      114.0
89075          Roberto Dueñas      221.0      137.0
5781           Tommy Burleson      223.0      102.0
6978          Arvydas Sabonis      223.0      122.0
89070                Yao Ming      226.0      141.0

In [30]:
bios.loc[(bios['name'].str.contains('Henry', case=False)) & (bios['born_country'] == 'USA')] # Filters for athletes with the word 'Henry' in them belonging to the USA

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
2234,2244,Henry Richardson,1889-05-19,Boston,Massachusetts,USA,United States,NaN,NaN,1963-11-19
5250,5269,Lea Henry,1961-11-22,Colquitt,Georgia,USA,United States,162.0,53.0,NaN
8740,8787,Henry Tillman,1960-08-01,Los Angeles,California,USA,United States,190.0,90.0,NaN
11468,11529,Henry Allen,1889-08-11,West Point,New York,USA,United States,NaN,NaN,1971-12-21
12045,12110,Frank Henry,1909-12-15,Cambridge,New York,USA,United States,NaN,NaN,1989-08-25
12046,12111,Guy Henry,1875-01-28,Fort Robinson,Nebraska,USA,United States,NaN,NaN,1967-11-29
15808,15919,"Henry O'Brien, Jr.",1910-04-05,San José,California,USA,United States,NaN,NaN,1973-04-18
20243,20387,Henry Clifford,1928-11-16,Staten Island,New York,USA,United States,183.0,77.0,2021-12-02
20255,20399,Henry Goode,1918-06-07,New York,New York,USA,United States,NaN,NaN,2000-04-30
20256,20400,Henry Greer,1899-10-11,New York,New York,USA,United States,NaN,NaN,1978-07-20
23487,23669,Henry Breckinridge,1886-05-25,Chicago,Illinois,USA,United States,185.0,NaN,1960-05-02
31150,31386,Henry Weyland,1873-09-09,Joplin,Missouri,USA,United States,NaN,NaN,1950-11-11
32756,33002,Henry Oehler,1916-03-22,New York,New York,USA,United States,NaN,NaN,1991-02-09
40531,40840,Henry Proctor,1929-10-19,Baxter Springs,Kansas,USA,United States,NaN,NaN,2005-04-13
40618,40928,Henry Welsford,1900-06-14,Pittston,Pennsylvania,USA,United States,179.0,NaN,1974-01-01
44268,44608,Henry Bailey,1893-04-24,Walterboro,South Carolina,USA,United States,170.0,NaN,1972-11-01
51040,51399,Jim Henry,1948-09-04,San Antonio,Texas,USA,United States,173.0,68.0,NaN
51112,51471,Henry Luning,1905-01-24,Honolulu,Hawaiʻi,USA,United States,NaN,NaN,1965-09-13
56569,56972,Henry Duey,1908-05-01,Chicago,Illinois,USA,United States,NaN,NaN,1993-02-13
56581,56984,Mark Henry,1971-06-12,Silsbee,Texas,USA,United States,190.0,NaN,NaN
60342,60775,Henry Szymanski,1898-07-04,Chicago,Illinois,USA,United States,NaN,NaN,1959-11-06
60368,60801,Henry Wittenberg,1918-09-18,Jersey City,New Jersey,USA,United States,NaN,NaN,2010-03-09
61447,61896,"Henry Duys, Jr.",1924-10-17,Montclair,New Jersey,USA,United States,NaN,NaN,2007-05-11
66184,66688,Henry Andrade,1962-04-17,Sacramento,California,USA,Cabo Verde,180.0,73.0,NaN
77551,78142,Henry Brawley,1876-10-07,Roxbury,Massachusetts,USA,United States,NaN,NaN,1954-02-11
77612,78203,Henry Carr,1942-11-27,Montgomery,Alabama,USA,United States,191.0,84.0,2015-05-29
77694,78285,Henry Cumming,1905-09-05,Augusta,Georgia,USA,United States,178.0,72.0,1945-07-10
77749,78340,Henry Dreyer,1911-02-02,Providence,Rhode Island,USA,United States,194.0,114.0,1986-05-27
77804,78395,Henry Field,1878-11-14,Slater,Missouri,USA,United States,NaN,NaN,1944-10-23
78146,78737,Henry Marsh,1954-03-15,Boston,Massachusetts,USA,United States,178.0,72.0,NaN
78458,79049,Henry Slack,1877-03-31,Chicago,Illinois,USA,United States,NaN,NaN,1928-07-18
81222,81874,LeeLee Morrison-Henry,1960-10-02,Norwood,Massachusetts,USA,Canada,172.0,59.0,NaN
83618,84280,Henry Boucha,1951-06-01,Warroad,Minnesota,USA,United States,186.0,84.0,2023-09-18
85907,86590,Ken Henry,1929-01-07,Chicago,Illinois,USA,United States,NaN,NaN,2009-03-01
86069,86755,Henry Homburger,1902-12-09,Saranac Lake,New York,USA,United States,NaN,NaN,1950-09-14
91452,92181,Henry Martineau,1904-12-24,Chicago,Illinois,USA,Great Britain,NaN,NaN,1972-02-23
91997,92729,Henry Nuzum,1977-03-04,Chapel Hill,North Carolina,USA,United States,190.0,96.0,NaN
115672,117037,Henry Cejudo,1987-02-09,Colorado Springs,Colorado,USA,United States,165.0,55.0,NaN
135237,138385,John-Henry Krueger,1995-03-27,Pittsburgh,Pennsylvania,USA,Hungary United States,178.0,75.0,NaN
143794,147450,Henry Leverett,2001-06-13,Bainbridge,Georgia,USA,United States,178.0,68.0,NaN

## Adding and Removing columns

In [43]:
coffee['price'] = 5

In [45]:
import numpy as np
coffee['new_price'] = np.where(coffee['Coffee Type'] == 'Espresso', 3, 6)

In [ ]:
coffee = coffee.drop(columns=['price'])
# Drops the column 'price' from the dataframe

In [ ]:
coffee = coffee.rename(columns={'new_price':'Updated Price'})
# Renames the column 'new_price' to 'Updated Price'

In [51]:
coffee

          Day Coffee Type  Units Sold  Updated Price
0      Monday    Espresso          25              3
1      Monday       Latte          15              6
2     Tuesday    Espresso          30              3
3     Tuesday       Latte          20              6
4   Wednesday    Espresso          35              3
5   Wednesday       Latte          25              6
6    Thursday    Espresso          40              3
7    Thursday       Latte          30              6
8      Friday    Espresso          45              3
9      Friday       Latte          35              6
10   Saturday    Espresso          45              3
11   Saturday       Latte          35              6
12     Sunday    Espresso          45              3
13     Sunday       Latte          35              6

In [52]:
bios_new = bios.copy()

In [55]:
bios_new['born_date'] = pd.to_datetime(bios_new['born_date']) # Converts the bord_date datatype from object to datetime64

bios_new['born_year'] = bios_new['born_date'].dt.year
bios_new[['name', 'born_year']]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [56]:
bios_new.to_csv('./data/bios_new.csv', index=False)